<h3> HOW BAD IS COVID IN CHICAGO (BY ZIPCODE)? </h3>
Data: Imported directly from the Chicago Data Portal

<h3> STEP 1</h3>
Let's read in up to 100,000 rows of COVID data for Chicago from the Chicago Data Portal.

In [5]:
import pandas as pd
import numpy as np
rawCOVID = pd.read_json('https://data.cityofchicago.org/resource/yhhz-zm2v.json?$limit=100000') #Import data directly from data portal
rawCOVID.head(10)

:@computed_region_43wa_7qmu  :@computed_region_6mkv_f3dw  \
0                         36.0                      14309.0   
1                         36.0                      14309.0   
2                         36.0                      14309.0   
3                         10.0                      14913.0   
4                         36.0                      14914.0   
5                         10.0                      14912.0   
6                         10.0                      14912.0   
7                         10.0                      14912.0   
8                         10.0                      14912.0   
9                         10.0                      14912.0   

   :@computed_region_bdys_3d7i  :@computed_region_rpca_8um6  \
0                        580.0                         42.0   
1                        580.0                         42.0   
2                        580.0                         42.0   
3                        368.0                         35.0   
4                         92.0                         46.0   
5                         92.0                         29.0   
6                         92.0                         29.0   
7                         92.0                         29.0   
8                         92.0                         29.0   
9                         92.0                         29.0   

   :@computed_region_vrxf_vc4k  case_rate_cumulative  case_rate_weekly  \
0                         38.0                6773.4             197.6   
1                         38.0                7822.8             136.3   
2                         38.0                8068.1             129.5   
3                         38.0                6192.1              65.4   
4                         38.0                2128.3              32.2   
5                         38.0               14961.6             383.6   
6                         38.0               15089.5             127.9   
7                         38.0               15217.4             127.9   
8                         38.0               15345.3             127.9   
9                         38.0               15345.3               0.0   

   cases_cumulative  cases_weekly  death_rate_cumulative  \
0             994.0          29.0                   75.0   
1            1148.0          20.0                   81.8   
2            1184.0          19.0                   81.8   
3            1704.0          18.0                   40.0   
4              66.0           1.0                   32.2   
5             117.0           3.0                    0.0   
6             118.0           1.0                    0.0   
7             119.0           1.0                    0.0   
8             120.0           1.0                    0.0   
9             120.0           0.0                    0.0   

                         ...                                 row_id  \
0                        ...                          60601-2021-12   
1                        ...                          60601-2021-31   
2                        ...                          60601-2021-33   
3                        ...                           60605-2021-9   
4                        ...                          60606-2020-37   
5                        ...                          60604-2021-33   
6                        ...                          60604-2021-34   
7                        ...                          60604-2021-35   
8                        ...                          60604-2021-36   
9                        ...                          60604-2021-37   

   test_rate_cumulative  test_rate_weekly  tests_cumulative  tests_weekly  \
0              156967.6            4197.6             23035         616.0   
1              234316.9            5267.5             34386         773.0   
2              248429.3            8327.1             36457        1222.0   
3              131098.5            3637.5        

We'll list the 26 column names

In [6]:
list(rawCOVID.columns)

[':@computed_region_43wa_7qmu',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 'case_rate_cumulative',
 'case_rate_weekly',
 'cases_cumulative',
 'cases_weekly',
 'death_rate_cumulative',
 'death_rate_weekly',
 'deaths_cumulative',
 'deaths_weekly',
 'percent_tested_positive_cumulative',
 'percent_tested_positive_weekly',
 'population',
 'row_id',
 'test_rate_cumulative',
 'test_rate_weekly',
 'tests_cumulative',
 'tests_weekly',
 'week_end',
 'week_number',
 'week_start',
 'zip_code',
 'zip_code_location']

Q1. .Does case matter when referring to a column name?
<hr>
<h3> STEP TWO </h3>
Let's streamline the data to just 4 columns, drop rows with missing data,  simplify the column names, and then display the first 20 rows.

In [7]:
COVID=rawCOVID[['deaths_cumulative', "population",  'tests_cumulative','zip_code']]
COVID.dropna  #drop rows with missing data
COVID.columns=["deaths","population","tests","zip"] #simplify the column names
COVID.head(20)

deaths  population  tests    zip
0       11       14675  23035  60601
1       12       14675  34386  60601
2       12       14675  36457  60601
3       11       27519  36077  60605
4        1        3101   2384  60606
5        0         782   6686  60604
6        0         782   6990  60604
7        0         782   7254  60604
8        0         782   7507  60604
9        0         782   7795  60604
10       0         782   7954  60604
11       1        3101   4655  60606
12       4       27519  12619  60605
13       1        3101   5092  60606
14       3        3101   7107  60606
15       3        3101   7575  60606
16       3        3101   7804  60606
17       3        3101   8480  60606
18       3        3101   8937  60606
19       3        3101   9139  60606

Q2. Of the zip codes listed, which has the smallest population?
<hr>
<h3> STEP THREE</h3>
Let's check how many rows have data in each column</h3>

In [8]:
COVID.count()

deaths        5040
population    5040
tests         5040
zip           5040
dtype: int64

Q3.  How many data rows are there in each column?
<hr>
<h3> STEP FOUR</h3>
Let's find out how many times each zip code appears.

In [9]:
COVID["zip"].value_counts()

60602      84
60649      84
60622      84
60605      84
60611      84
60613      84
60638      84
60626      84
60641      84
60647      84
60659      84
60657      84
60634      84
60610      84
60614      84
60644      84
60615      84
60625      84
60651      84
60604      84
60827      84
60619      84
Unknown    84
60656      84
60628      84
60630      84
60617      84
60612      84
60637      84
60655      84
60646      84
60707      84
60653      84
60640      84
60661      84
60601      84
60639      84
60603      84
60666      84
60607      84
60654      84
60623      84
60609      84
60624      84
60620      84
60608      84
60629      84
60621      84
60606      84
60645      84
60632      84
60633      84
60636      84
60631      84
60616      84
60642      84
60660      84
60643      84
60652      84
60618      84
Name: zip, dtype: int64

<h2>STEP FIVE </h2>
Let's make a copy of the COVID dataframe and display the first 5 rows.

In [11]:
df1=COVID
df1.head(5)

deaths  population  tests    zip
0      11       14675  23035  60601
1      12       14675  34386  60601
2      12       14675  36457  60601
3      11       27519  36077  60605
4       1        3101   2384  60606

<h2> STEP SIX </h2> 

Filter data by a specific zip code, for example, '60611'

In [16]:
df2=df1[df1['zip']=='60611']
df2.head()

deaths  population  tests    zip
81       3       32426   7196  60611
82       3       32426   7930  60611
83       4       32426  15110  60611
84       4       32426  16286  60611
85       5       32426  25846  60611

<h2> STEP SEVEN </h2>
Let's find the largest value in the 'tests' column for zip '60611'.

In [19]:
df2 = COVID[df1["zip"]=='60611'] #get just rows with zip 60611
numtested=df2["tests"].max() #get the largest number for tests
numtested

81747

Question:  How can we find how many deaths due to COVID have occurred in zip '60623'?  (Create a new dataframe for 60623 called temp)

In [20]:
temp = COVID[df1["zip"]=='60623'] #get just rows with zip 60611
numdeaths=temp["deaths"].max() #get the largest number for tests
numdeaths

276

Question: How can we get the population in 60623?

In [21]:
df = COVID[COVID["zip"]=='60623'] #get just rows with zip 60611
population=df["population"].max() #get the largest number for tests
population

85979

<h3> STEP EIGHT</h3>
We can instruct the computer to give us the number COVID tests for any Chicago zipcode. </h3>

In [22]:
def MyCOVID(COVID,zip):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zip and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zip]
            numtested=df["tests"].max()
            print("Zip code: ", zip)  #print zipcode
            print("number tested is ", numtested) #print number tested
    return ("Enter a different zip code if you wish.")

Q5. Test out the function on zip code '60610'

In [23]:
MyCOVID(COVID,'60610')

Zip code:  60610
number tested is  105952


'Enter a different zip code if you wish.'

<h3> Assignment </h3>

Q1)  Define a function myCOVID2() which outputs for each given zip code the population, number tested, and number of deaths. 

In [24]:
#ans to Q1
def MyCOVID2(COVID,zip):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zip and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zip]
            population=df["population"].max()
            numtested=df["tests"].max()
            deaths=df["deaths"].max()
            print("Zip code: ", zip)  #print zipcode
            print("population is ", population) #print population
            print("number tested is ", numtested) #print number tested
            print("number deaths is ", deaths) #print number deaths
    return ("Enter a different zip code if you wish.")

Q2)  Use your function myCOVID2() to determine the COVID data for each of the following Chicago landmarks:

a) North Park University (zip  '60625')


In [25]:
#ans to 2a)
MyCOVID2(COVID,'60625')

Zip code:  60625
population is  79243
number tested is  170462
number deaths is  202


'Enter a different zip code if you wish.'

b) University of Chicago and Wheaton in Chicago (zip='60637')

In [26]:
MyCOVID2(COVID,'60637')

Zip code:  60637
population is  47454
number tested is  178861
number deaths is  71


'Enter a different zip code if you wish.'

c) Lawndale Community Church (zip='60623')

In [27]:
MyCOVID2(COVID,'60623')

Zip code:  60623
population is  85979
number tested is  138862
number deaths is  276


'Enter a different zip code if you wish.'

Q3) Why is COVID disproportionately impacting black and brown communities?

ans to Q3:

Disproportionately high percentage of front line workers are black and brown, including those offering COVID-19 care.  Access to good health care is more limited in disadvantaged communities, and there is discrimination  in healthcare in other communities.